In [1]:
# 1. Import numpy as np and see the version 

import numpy as np
np.__version__

'1.18.1'

In [6]:
# 2. How to create a 1D array?

a=np.array([1,2,3,4,5])
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

In [18]:
# 3.  How to create a boolean array? 

a=np.array(['','asd',False,True,0,1],dtype=bool)
print(a)


[False  True False  True False  True]


In [19]:
# 4. How to extract items that satisfy a given condition from 1D array? 

a=np.array([1,2,3,4,5])
for i in a:
    if i%2==0:
        print(i)

2
4


In [23]:
# 5. How to replace items that satisfy a condition with another value in numpy array?

a=np.array([1,2,3,4,5])
print(a)
np.where(a>3,0,a)

[1 2 3 4 5]


array([1, 2, 3, 0, 0])

In [28]:
# 6. How to replace items that satisfy a condition without affecting the original array? 

a=np.array([1,2,3,4,5])
b=a
print('array a:',a)
print('array b:',b)
print('modified array b:',np.where(b>3,0,b))
print('original array a:',a)

array a: [1 2 3 4 5]
array b: [1 2 3 4 5]
modified array b: [1 2 3 0 0]
original array a: [1 2 3 4 5]


In [30]:
# 7. How to reshape an array? 

a=np.array([1,2,3,4,5,6])
print(a)
a=np.reshape(a,(3,2))
print(a)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [32]:
# 8. How to stack two arrays vertically? 

a=np.array([1,2,3,4,5,6])
print(np.vstack(a))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [33]:
# 9. How to stack two arrays horizontally? 

a=np.array([1,2,3,4,5,6])
print(np.hstack(a))

[1 2 3 4 5 6]


In [11]:
# 10. How to generate custom sequences in numpy without hardcoding? 

a=np.array([1,2,3,4,5,6])
np.tile(a,3),np.repeat(a,3)

(array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]),
 array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6]))

In [13]:
# 11. How to get the common items between two python numpy arrays? 

a=np.array([1,2,3,4,5,6])
b=np.array([4,5,6,7,8,9])
np.intersect1d(a,b)

array([4, 5, 6])

In [14]:
# 12.  How to remove from one array those items that exist in another? 

a=np.array([1,2,3,4,5,6])
b=np.array([4,5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3])

In [23]:
# 13. How to get the positions where elements of two arrays match? 

a=np.array([1,2,3,4,5,6])
b=np.array([7,8,9,4,5,6])
np.where(a==b)

(array([3, 4, 5], dtype=int64),)

In [29]:
# 14. How to extract all numbers between a given range from a numpy array? 

a=np.array([1,2,3,4,5,6,7,8,9])
a[(a>2) & (a<8)]

array([3, 4, 5, 6, 7])

In [ ]:
# 15. How to make a python function that handles scalars to work on numpy arrays? 

In [31]:
# 16. How to swap two columns in a 2d numpy array? 

a=np.array([[1,2,3,4,5,6],[7,8,9,4,5,6]])
a

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 4, 5, 6]])

In [2]:
#17.How to swap two rows in a 2d numpy array?
my_arr = np.arange(9).reshape(3, 3)
print("Original array:")
print(my_arr)
my_arr[[0, 1],:] = my_arr[[1, 0],:]
print("\nAfter swapping arrays:")
print(my_arr)


Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

After swapping arrays:
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [3]:
#18:How to reverse the rows of a 2D array?
arr1 = np.arange(12).reshape(3,4)
arr1[::-1]


array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [4]:
#19.How to reverse the columns of a 2D array?
arr1 = np.arange(12).reshape(3,4)
arr1[:, ::-1]


array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

In [5]:
#20.How to create a 2D array containing random floats between 5 and 10?
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)


[[8.97336044 8.61223181 5.69254063]
 [8.96011356 5.63493469 7.75955511]
 [7.02909811 9.42057976 7.4313723 ]
 [9.4468243  9.70293024 7.56447915]
 [8.70065513 6.12039399 5.96830182]]


In [6]:
#21. How to print only 3 decimal places in python numpy array?
rand_arr = np.random.random([5,3])
np.set_printoptions(precision=3)
print(rand_arr)


[[0.258 0.712 0.996]
 [0.513 0.421 0.344]
 [0.988 0.02  0.401]
 [0.273 0.009 0.68 ]
 [0.504 0.974 0.08 ]]


In [7]:

#23. How to limit the number of items printed in output of numpy array?
np.set_printoptions(threshold=6)
arr = np.arange(15)
print(arr)


[ 0  1  2 ... 12 13 14]


In [8]:
#24. How to print the full numpy array without truncating
import sys
arr = np.arange(10)
np.set_printoptions(threshold=sys.maxsize)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [9]:
#28. How to compute the mean, median, standard deviation of a numpy array?
x = np.arange(6)
print("\nOriginal array:")
print(x)
r1 = np.mean(x)
r2 = np.average(x)
assert np.allclose(r1, r2)
print("\nMean: ", r1)
r1 = np.std(x)
r2 = np.sqrt(np.mean((x - np.mean(x)) ** 2 ))
assert np.allclose(r1, r2)
print("\nstd: ", 1)
r1= np.var(x)
r2 = np.mean((x - np.mean(x)) ** 2 )
assert np.allclose(r1, r2)
print("\nvariance: ", r1)



Original array:
[0 1 2 3 4 5]

Mean:  2.5

std:  1

variance:  2.9166666666666665


In [10]:
#28. How to compute the mean, median, standard deviation of a numpy array?
x = np.arange(6)
print("\nOriginal array:")
print(x)
r1 = np.mean(x)
r2 = np.average(x)
assert np.allclose(r1, r2)
print("\nMean: ", r1)
r1 = np.std(x)
r2 = np.sqrt(np.mean((x - np.mean(x)) ** 2 ))
assert np.allclose(r1, r2)
print("\nstd: ", 1)
r1= np.var(x)
r2 = np.mean((x - np.mean(x)) ** 2 )
assert np.allclose(r1, r2)
print("\nvariance: ", r1)



Original array:
[0 1 2 3 4 5]

Mean:  2.5

std:  1

variance:  2.9166666666666665


In [11]:
#48.How to get the positions of top n values from a numpy array?
np.random.seed(100)
a = np.random.uniform(1,50, 20)
np.argpartition(-a, 5)[:5]


array([15, 10,  3,  7, 18], dtype=int64)

In [12]:
#50.How to convert an array of arrays into a flat 1d array?
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
array_of_arrays = np.array([arr1, arr2, arr3])
print('array_of_arrays: ', array_of_arrays)
arr_2d = np.concatenate(array_of_arrays)
print(arr_2d)


array_of_arrays:  [array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]
[0 1 2 3 4 5 6 7 8 9]


In [13]:
#51.How to generate one-hot encodings for an array in numpy?
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
print(arr)
(arr[:, None] == np.unique(arr)).view(np.int8)


[2 3 2 2 2 1]


array([[0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]], dtype=int8)

In [14]:
#54. How to rank items in an array using numpy?
np.random.seed(10)
a = np.random.randint(20, size=10)
print('Array: ', a)
print(a.argsort().argsort())
print('Array: ', a)


Array:  [ 9  4 15  0 17 16 17  8  9  0]
[4 2 6 0 8 7 9 3 5 1]
Array:  [ 9  4 15  0 17 16 17  8  9  0]


In [15]:
#55.How to rank items in a multidimensional array using numpy?
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)
print(a.ravel().argsort().argsort().reshape(a.shape))


[[ 9  4 15  0 17]
 [16 17  8  9  0]]
[[4 2 6 0 8]
 [7 9 3 5 1]]


In [16]:
#56. How to find the maximum value in each row of a numpy array 2d?
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)
np.amax(a, axis=1)


[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]


array([9, 8, 6, 3, 9])

In [17]:
#57. How to compute the min-by-max for each row for a numpy array 2d?
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)


[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]


In [21]:
#61. How to drop all missing values from a numpy array?
np.array([1,2,3,np.nan,5,6,7,np.nan])
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a[~np.isnan(a)]


array([1., 2., 3., 5., 6., 7.])

In [22]:
#62. How to compute the euclidean distance between two arrays?
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
dist = np.linalg.norm(a-b)
print(dist)


6.708203932499369


In [23]:
#63.How to find all the local maxima (or peaks) in a 1d array?
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations


array([2, 5], dtype=int64)

In [25]:
#64:How to subtract a 1d array from a 2d array, where each item of 1d array subtracts from respective row?
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
print(a_2d - b_1d[:,None])


[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [26]:
#65.How to find the index of n’th repetition of an item in an array
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5
[i for i, v in enumerate(x) if v == 1][n-1]


8

In [27]:
#66. How to convert numpy’s datetime64 object to datetime’s datetime object?
dt64 = np.datetime64('2018-02-25 22:10:10')
from datetime import datetime
dt64.astype(datetime)


datetime.datetime(2018, 2, 25, 22, 10, 10)

In [28]:
#67.How to compute the moving average of a numpy array?
np.random.seed(100)
Z = np.random.randint(10, size=10)
print('array: ', Z)
moving_average(Z, n=3).round(2)


array:  [8 8 3 7 7 0 4 2 5 2]


NameError: name 'moving_average' is not defined

In [29]:
#68.How to create a numpy array sequence given only the starting point, length and the step?
length = 10
start = 5
step = 3
def seq(start, length, step):
    end = start + (step*length)
    return np.arange(start, end, step)
seq(start, length, step)


array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])